services:
  server:
    build: ./backend
    ports:
      - 3000:3000
    command: sh -c "CHOKIDAR_USEPOLLING=true npm run start"
    volumes:
      - ./backend/src/:/app/src/
  client:
    build: ./frontend
    ports: 
      - 8088:5173
    command: sh -c "CHOKIDAR_USEPOLLING=true npm run dev"
    volumes:
      - ./frontend/src/:/app/src/
